openmrs.root.url: https://localhost.localdomain/openmrs/ws/rest/v1
bahmni.login.url: https://localhost.localdomain/bahmni/home/#/login?showLoginMessage
reports.url: https://localhost.localdomain/bahmnireports/report
reports.json: /var/www/bahmni_config/openmrs/apps/reports/reports.json
dhis.config.directory: /var/www/bahmni_config/dhis2/
dhis.url: dhisinstanceurl
dhis.user: user
dhis.password: password
dhis.ewars.url: http://103.69.126.98/ewars/
dhis.ewars.user: bayalpata.hospital
dhis.ewars.password: Diwash@789
openmrs.db.url: jdbc:mysql://localhost.localdomain/openmrs?user=root&password=password
openelis.db.url: jdbc:mysql://localhost.localdomain/openmrs?user=dbuser&password=dbpassword
log4j.config.file: log4j.properties
server.port: 8040
server.context-path: /dhis-integration/
submission.audit.folder: /dhis-integration-data